#
# Copyright (C) 2011 Red Hat, Inc.
# Written by Jason Guiditta <jguiditt@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.  A copy of the GNU General Public License is
# also available at http://www.gnu.org/copyleft/gpl.html.

require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'spec/rake/spectask'
require 'rake/rpmtask'

RPMBUILD_DIR = "#{File.expand_path('~')}/rpmbuild"
RPM_SPEC = "rubygem-image_factory_connector.spec"


spec = Gem::Specification.new do |s|
  s.name = 'image_factory_connector'
  s.version = '0.0.3'
  s.has_rdoc = true
  #s.extra_rdoc_files = ['README', 'LICENSE']
  s.summary = 'Sinatra microapp to talk to  Aeolus Image Factory QMF console'
  s.description = 'REST api and callback mechanism to wrap qmf for the Aeolus project'
  s.author = 'Jason Guiditta'
  s.email = 'jguiditt@redhat.com'
  s.license = 'GPL-2'
  s.homepage = 'http://aeolusproject.org'
  s.executables = ['image_factory_connector']
  s.files = %w( Rakefile) + Dir.glob("{bin,lib,spec}/**/*")
  s.require_path = "lib"
  s.bindir = "bin"
  s.requirements << 'Requires QMF version 2 (0.8-x series on fedora)'
  s.add_dependency('image_factory_console', '>=0.2.0')
  s.add_dependency('builder', '~>2.1.2')
  s.add_dependency('sinatra', '~>1.0')
  s.add_dependency('typhoeus', '~>0.1.31')

  s.add_development_dependency('rspec', '~>1.3.0')

end

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end

Rake::RDocTask.new do |rdoc|
  files =['lib/**/*.rb']
  rdoc.rdoc_files.add(files)
  #rdoc.main = "README" # page to start on
  rdoc.title = "image_factory_connector Docs"
  rdoc.rdoc_dir = 'doc/rdoc' # rdoc output folder
  rdoc.options << '--line-numbers'
end

Spec::Rake::SpecTask.new do |t|
  t.spec_files = FileList['spec/**/*.rb']
end

Rake::RpmTask.new(RPM_SPEC) do |rpm|
  rpm.need_tar = true
  rpm.package_files.include("bin/*", "lib/**/*")
  rpm.topdir = "#{RPMBUILD_DIR}"
end
