#!/bin/bash
#
#
# conductor-condor_refreshd       startup script for conductor-condor_refreshd
#
# chkconfig: - 99 01
# description: conductor-condor_refreshd populates the Conductor scheduler
#    from the Aeolus Conductor db

[ -r /etc/sysconfig/conductor-rails ] && . /etc/sysconfig/conductor-rails

[ -r /etc/sysconfig/aeolus-conductor ] && . /etc/sysconfig/aeolus-conductor

CONDUCTOR_DIR="${CONDUCTOR_DIR:-/usr/share/aeolus-conductor}"
REFRESHD_LOG="${REFRESHD_LOG:-/var/log/aeolus-conductor/condor_refreshd.log}"
REFRESHD_PID="${REFRESHD_PID:-/var/run/aeolus-conductor/condor_refreshd.pid}"
REFRESHD_LOCKFILE="${REFRESHD_LOCKFILE:-/var/lock/subsys/conductor-condor_refreshd}"
AEOLUS_USER="${AEOLUS_USER:-aeolus}"

REFRESHD_PATH=$CONDUCTOR_DIR/condor_refreshd
REFRESHD_PROG=condor_refreshd

. /etc/init.d/functions

start() {
    echo -n "Starting conductor-condor_refreshd: "

    daemon --user=$AEOLUS_USER $REFRESHD_PATH/$REFRESHD_PROG
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && touch $REFRESHD_LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

stop() {
    echo -n "Shutting down conductor-condor_refreshd: "
    killproc -p $REFRESHD_PID $REFRESHD_PROG
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && rm -f $REFRESHD_LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

case "$1" in
    start)
      start
     ;;
    stop)
      stop
      ;;
    restart)
      stop
      start
      ;;
    reload)
      ;;
    force-reload)
      restart
      ;;
    status)
     status -p $REFRESHD_PID $REFRESHD_PROG
     RETVAL=$?
     ;;
    *)
      echo "Usage: conductor-condor_refreshd {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
