#!/bin/bash
#
#
# conductor-image_builder_service       startup script for conductor-image_builder_service
#
# chkconfig: - 93 07
# description: conductor-image_builder_service builds cloud images
#    from the Aeolus Conductor db

[ -r /etc/sysconfig/conductor-rails ] && . /etc/sysconfig/conductor-rails

[ -r /etc/sysconfig/aeolus-conductor ] && . /etc/sysconfig/aeolus-conductor

CONDUCTOR_DIR="${CONDUCTOR_DIR:-/usr/share/aeolus-conductor}"
BUILDER_LOG="${BUILDER_LOG:-/var/log/aeolus-conductor/image_builder_service.log}"
BUILDER_PID="${BUILDER_PID:-/var/run/aeolus-conductor/image_builder_service.pid}"
BUILDER_LOCKFILE="${BUILDER_LOCKFILE:-/var/lock/subsys/conductor-image_builder_service}"
AEOLUS_USER="${AEOLUS_USER:-aeolus}"

BUILDER_PATH=$CONDUCTOR_DIR/image_builder_service
BUILDER_PROG=image_builder_service

. /etc/init.d/functions

start() {
    echo -n "Starting conductor-image_builder_service: "

    daemon --user=$AEOLUS_USER $BUILDER_PATH/$BUILDER_PROG
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && touch $BUILDER_LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

stop() {
    echo -n "Shutting down conductor-image_builder_service: "
    killproc -p $BUILDER_PID $BUILDER_PROG
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && rm -f $BUILDER_LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

case "$1" in
    start)
      start
     ;;
    stop)
      stop
      ;;
    restart)
      stop
      start
      ;;
    reload)
      ;;
    force-reload)
      restart
      ;;
    status)
     status -p $BUILDER_PID $BUILDER_PROG
     RETVAL=$?
     ;;
    *)
      echo "Usage: conductor-image_builder_service {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
