#!/bin/bash
#
#
# deltacloud-aggregator       startup script for deltacloud-aggregator
#
# chkconfig: - 99 01
# description: deltacloud-aggregator is primary server process for the \
#    Deltacloud Aggregator.
#

[ -r /etc/sysconfig/deltacloud-rails ] && . /etc/sysconfig/deltacloud-rails

[ -r /etc/sysconfig/deltacloud-aggregator ] && . /etc/sysconfig/deltacloud-aggregator

RAILS_ENV="${RAILS_ENV:-production}"
DELTACLOUD_DIR="${DELTACLOUD_DIR:-/usr/share/deltacloud-aggregator}"
THIN_LOG="${THIN_LOG:-/var/log/deltacloud-aggregator/thin.log}"
THIN_PID="${THIN_PID:-/var/run/deltacloud-aggregator/thin.pid}"
THIN_LOCKFILE="${THIN_LOCKFILE:-/var/lock/subsys/deltacloud-aggregator }"
USER="${USER:-dcloud}"
GROUP="${GROUP:-dcloud}"
PREFIX="${PREFIX:-/deltacloud}"
ADAPTER="${ADAPTER:-rails}"

THIN_PROG=thin
ADDR=127.0.0.1
RETVAL=0

. /etc/init.d/functions

start() {
    echo -n "Starting deltacloud-aggregator: "

    $THIN_PROG start -c $DELTACLOUD_DIR -l $THIN_LOG -P $THIN_PID \
	-a $ADDR -e $RAILS_ENV --user $USER --group $GROUP \
	-d --prefix=$PREFIX -A $ADAPTER
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && touch $THIN_LOCKFILE ; then
	echo_success
	echo
    else
	echo_failure
	echo
    fi

}

stop() {
    echo -n "Shutting down deltacloud-aggregator: "
    $THIN_PROG stop -c $DELTACLOUD_DIR -P $THIN_PID
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && rm -f $THIN_LOCKFILE ; then
	echo_success
	echo
    else
	echo_failure
	echo
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    reload)
        ;;
    force-reload)
        restart
        ;;
    status)
	status $THIN_PROG
	RETVAL=$?
	;;
    *)
      echo "Usage: deltacloud-aggregator {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
