#!/bin/bash
#
#
# deltacloud-dbomatic       startup script for deltacloud-dbomatic
#
# chkconfig: - 99 01
# description: deltacloud-dbomatic populates the Deltacloud Aggregator
#    db from the Deltacloud scheduler's output.

[ -r /etc/sysconfig/deltacloud-rails ] && . /etc/sysconfig/deltacloud-rails

[ -r /etc/sysconfig/deltacloud-aggregator ] && . /etc/sysconfig/deltacloud-aggregator

DELTACLOUD_DIR="${DELTACLOUD_DIR:-/usr/share/deltacloud-aggregator}"
DBOMATIC_LOG="${DBOMATIC_LOG:-/var/log/deltacloud-aggregator/dbomatic.log}"
DBOMATIC_PID="${DBOMATIC_PID:-/var/run/deltacloud-aggregator/dbomatic.pid}"
DBOMATIC_LOCKFILE="${DBOMATIC_LOCKFILE:-/var/lock/subsys/deltacloud-dbomatic }"
DCLOUD_USER="${DCLOUD_USER:-dcloud}"

DBOMATIC_PATH=/usr/share/deltacloud-aggregator/dbomatic
DBOMATIC_PROG=dbomatic

. /etc/init.d/functions

start() {
    echo -n "Starting deltacloud-dbomatic: "

    daemon --user=$DCLOUD_USER $DBOMATIC_PATH/$DBOMATIC_PROG
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && touch $DBOMATIC_LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

stop() {
    echo -n "Shutting down deltacloud-dbomatic: "
    killproc -p $DBOMATIC_PID $DBOMATIC_PROG
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && rm -f $DBOMATIC_LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

case "$1" in
    start)
      start
     ;;
    stop)
      stop
      ;;
    restart)
      stop
      start
      ;;
    reload)
      ;;
    force-reload)
      restart
      ;;
    status)
     status -p $DBOMATIC_PID $DBOMATIC_PROG
     RETVAL=$?
     ;;
    *)
      echo "Usage: deltacloud-dbomatic {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
