.TH aeolus-image 1  "July 07, 2011" "version 0.4" "USER COMMANDS"
.SH NAME
aeolus-image \- command for listing aeolus image associated objects.
.SH SYNOPSIS
.B aeolus-image list [\-h|--help] [\-u|--username] [\-w|--password] [\-i|--images] [\-b|--builds [image id]] [\-t|--targetimages [build id]] [\-g|--targets] [\-a|--accounts] [\-p|--providers]
.SH DESCRIPTION
aeolus-image list commands allows users to list information on the contents of particular objects in image warehouse including:
.B images: high level image represenation associated with underlying provider and target images.
.B builds: an object representation of a particular build that has taken place for a high level image
.B targets: particular targets available to build agains, for example 'ec2'
.B targetimages: represents builds of particular image against a target.  For example building against target 'ec2' would create an AMI specific image
.B providerimages: represents the actual images that have been uploaded to a provider.  Similiar to a target image but specific to a particular provider
.SH OPTIONS
.TP
\-u, --user <username>
Conductor username
.TP
\-w, --password <password>
Conductor password
Get usage information for this command and associated commmands
.TP
\-i, --images
Retrieve a list of images
.TP
\-b, --builds <image id>
Retrieve the builds of an image
.TP
\-t, --targetimages <build id>
Retrieve the target images from a build
.TP
\-P, --providerimages
Retrieve the provider images from a target image
.TP
\-g, --targets
Retrieve a list of availabe targets
.TP
\-p, --providers
Retrieve a list of available providers
.TP
\-a, --accounts
Retrieve a list of available accounts
.TP
\-d, --daemon
Run as a background process
.TP
\-h, --help
.SH EXAMPLES
.TP
List all images
.B aeolus-image list
\--images
.TP
List all builds for an image with id: 12345678-aaaa-1234--1234567890ab
.B aeolus-image list
\--builds 12345678-aaaa-1234--1234567890ab
.TP
List all target images for a given build with id: 12345678-bbbb-1234--1234567890ab
.B aeolus-image list
\--builds 12345678-bbbb-1234--1234567890ab
.TP
List all available targets
.B aeolus-image list
\--targets
.TP
List all available providers
.B aeolus-image list
\--providers
.TP
List all available accounts
.B aeolus-image list
\--account
.SH AUTHOR
Martyn Taylor (mtaylor@redhat.com), Jason Guiditta (jguiditta@redhat.com)
.SH SEE ALSO
aeolus-image-build(1), aeolus-image-push(1), aeolus-image-import(1), aeolus-image-delete(1)
