.TH aeolus-image 1  "July 07, 2011" "version 0.4" "USER COMMANDS"
.SH NAME
aeolus-image \- command line tool for managing aeolus images
.SH SYNOPSIS
.B aeolus-image
[\-h]
.SH DESCRIPTION
aeolus-image is a tool that allows users to control their aeolus images through image builder and aeolus conductor.  aeolus-image offers four commands options; list, build, push, import.  For more information on each command please run man aeolus-image <command> or aeolus-image --help
.SH OPTIONS
.TP
\-h, --help
Get usage information for this tool and subcommands
.SH AUTHOR
Martyn Taylor (mtaylor@redhat.com), Jason Guiditta (jguiditta@redhat.com)
.SH SEE ALSO
aeolus-image-build(1), aeolus-image-push(1), aeolus-image-list(1), aeolus-image-import(1)
