#!/usr/bin/ruby
init_scripts=%w(aeolus-conductor deltacloud-core httpd imagefactory iwhd libvirtd mongod ntpd postgresql)

init_scripts.each do |script|
	puts "\nChecking #{script} ..."
        cmd = "/etc/init.d/#{script} status"
	out = `#{cmd}`
	if $?.to_i == 0
		puts " \e[1;32mSuccess:\e[0m #{out.strip}"
	else
		puts " \e[1;31mFAILURE:\e[0m #{out.strip}"
	end
end
