source 'https://rubygems.org'

# This is a recent commit on the rails 3-2-stable branch.
# We were previously in between 3.2.11 and 3.2.12, before 3.2.12 was
# released, to work around this issue introduced in 3.2.11:
# https://github.com/rails/rails/pull/8895#issuecomment-12156101
# 3.2.12 was a security-only fix, without this fix, so we just
# advanced up the tree. 3.2.13, or whatever the next bug-fix release
# is, should let us get back on 'normal' Rails.
gem 'rails', :git => "git://github.com/rails/rails", :ref => '7f4975ffc618bc3125039c565507a385c1187183'

gem 'deltacloud-client', :require => 'deltacloud'
gem 'mustache'
gem 'will_paginate', '>= 3.0.pre1'
gem 'nokogiri'
gem 'simple-navigation'
gem 'rest-client'
gem 'rack-restful_submit'
gem 'uuidtools'
gem 'pg'
gem 'thin'
gem 'json'
gem 'rails_warden'
gem 'ruby-net-ldap', :require => 'net/ldap'
gem 'oauth'
gem 'ldap_fluff'
gem 'tim'
gem 'delayed_job', '~> 2.1.4'
gem 'paranoia'
gem 'simple_form', '~> 2.0.3'
gem 'haml-rails'
gem 'sass-rails'
gem 'compass-rails'
gem "alchemy", ">= 1.0.1"
gem 'gettext_i18n_rails'
gem 'cbf', ">= 0.0.3"

platforms :ruby_18 do
  gem 'fastercsv'
  gem 'require_relative'
end

group :assets do
  gem 'uglifier'
  gem 'therubyracer'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails', '~> 1.4.0'
  gem 'timecop'
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem 'vcr', '< 2.0.0'
  gem 'webmock'
  gem 'launchy'
  gem 'gettext', '>=1.9.3', :require => false
  gem 'ruby_parser', :require => false
end
