source :rubygems

# This is in between 3.2.11 and 3.2.12, and should be removed once 3.2.12 is released.
# See - https://github.com/rails/rails/pull/8895#issuecomment-12156101
gem 'rails', :git => "git://github.com/rails/rails", :ref => '63970dc7db273551f977483109dde936c8a7554f'

gem 'deltacloud-client', :require => 'deltacloud'
gem 'sass'
gem 'haml'
gem 'mustache'
gem 'will_paginate', '>= 3.0.pre1'
gem 'nokogiri'
gem 'simple-navigation'
gem 'rest-client'
gem 'rack-restful_submit'
gem 'uuidtools'
gem 'pg'
gem 'thin'
gem 'json'
gem 'rails_warden'
gem 'ruby-net-ldap', :require => 'net/ldap'
gem 'oauth'
gem 'ldap_fluff'
gem 'compass', '>= 0.12.2'
gem 'compass-960-plugin', '>= 0.10.4', :require=> 'ninesixty'
gem 'delayed_job', '~> 2.1.4'
gem 'paranoia'
gem 'simple_form', '~> 2.0.3'
gem 'tim'

platforms :ruby_18 do
  gem 'fastercsv'
  gem 'require_relative'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails', '~> 1.4.0'
  gem 'timecop'
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem 'vcr', '< 2.0.0'
  gem 'webmock'
  gem 'launchy'
end
